spring:
#  data:
#    mongodb:
##      uri: "mongodb://root:example@localhost:27017/demo?authSource=admin"
#  redis:
#    port: 6379
#    host: redis

logging:
  level:
    root: INFO

management:
  health:
    mongo:
      enabled: false